name: project_wombat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  http: ^0.13.5
  peerdart: ^0.5.0
  rsa_encrypt: ^2.0.0
  tcp_socket_connection: ^0.3.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.22.0
  web_socket_channel: ^2.3.0

flutter:
  uses-material-design: true
